permalink:  /:year/:month/:day/:title
auto: true
safe: false
pygments: false


# Twitter
twitter_user: grep_alex
twitter_tweet_count: 10
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true